apiVersion: v1
kind: ConfigMap
metadata:
  name: pagecolour
data:
  # Configuration values can be set as key-value properties
  COLOUR: red
  # Or set as complete file contents (even JSON!)
  # keys: |
  #   image.public.key=771
  #   rsa.public.key=42
  # 
  #  or from cmd: k create configmap pagecolour --from-literal=COLOUR=red
