apiVersion: v1
kind: Service
metadata:
  labels:
    run: web-server-depl
  name: web-server-depl
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: web-server-depl
  type: LoadBalancer
